# Generated by Django 4.0.10 on 2023-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_localities'),
    ]

    operations = [
        migrations.AddField(
            model_name='localities',
            name='search_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='localities',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
