# Generated by Django 4.0.10 on 2023-03-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_localities_search_description_localities_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='localities',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
